# Generated by Django 2.2.6 on 2019-10-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
