# Generated by Django 2.2.6 on 2019-12-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_auto_20191021_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='key',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
